CREATE TABLE LOCALITA (
    CODICE_ISTAT INT,
    CAP INT,
    SIGLA_PROVINCIA VARCHAR(3) NOT NULL,
    DENOMINAZIONE_PROVINCIA VARCHAR(100) NOT NULL,
    DENOMINAZIONE_REGIONE VARCHAR(40) NOT NULL,
    DENOMINAZIONE_LOCALITA VARCHAR(200) NOT NULL,
    PRIMARY KEY (CODICE_ISTAT, CAP)
);