-- DDL di creazione della tabella contentente le informazioni riguardanti l'anagrafica BUSINESS PARTNER del fornitore
CREATE TABLE ANAGRAFICA_FORNITORI (
    CODICE_FORNITORE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    COGNOME VARCHAR(40) NOT NULL,
    RAGIONE_SOCIALE VARCHAR(200) NOT NULL,
    PARTITA_IVA VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    CODICE_FISCALE VARCHAR(16) NULL,
    CAP INT NOT NULL,
    CODICE_ISTAT INT NOT NULL,
    INDIRIZZO VARCHAR(200) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    PHONE_NUMBER BIGINT(10) NULL,
    RUOLO VARCHAR(10) DEFAULT 'FORNITORE',
    DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_MODIFICA TIMESTAMP NULL,
    FOREIGN KEY (CODICE_ISTAT, CAP) REFERENCES LOCALITA(CODICE_ISTAT, CAP)
)