-- DDL database
CREATE DATABASE magicshelf;

-- 1. DDL tabella della Località

CREATE TABLE LOCALITA (
    CODICE_ISTAT INT PRIMARY KEY,
    CAP INT NOT NULL,
    PROVINCIA VARCHAR(20) NOT NULL,
    REGIONE VARCHAR(20) NOT NULL,
    LOCALITA VARCHAR(20) NOT NULL
);

-- 2. DDL tabella dei clienti

CREATE TABLE ANAGRAFICA_CLIENTI (
    CODICE_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    COGNOME VARCHAR(40) NOT NULL,
    CAP INT NOT NULL,
    CODICE_ISTAT INT NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    PHONE_NUMBER INT NULL,
    DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_MODIFICA TIMESTAMP NULL,
    FOREIGN KEY (CODICE_ISTAT) REFERENCES LOCALITA(CODICE_ISTAT)
);

-- 3. DDL tabella dei fornitori

CREATE TABLE ANAGRAFICA_FORNITORI (
    CODICE_FORNITORE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    COGNOME VARCHAR(40) NOT NULL,
    RAGIONE_SOCIALE VARCHAR(200) NOT NULL,
    PARTITA_IVA VARCHAR(16) NOT NULL,
    CODICE_FISCALE VARCHAR(16) NULL,
    CAP INT NOT NULL,
    CODICE_ISTAT INT NOT NULL,
    INDIRIZZO VARCHAR(200) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    PHONE_NUMBER INT NULL,
    DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_MODIFICA TIMESTAMP NULL,
    FOREIGN KEY (CODICE_ISTAT) REFERENCES LOCALITA(CODICE_ISTAT)
);

-- 4. DDL tabella dei materiali 

CREATE TABLE ANAGRAFICA_MATERIALI (
    CODICE_MATERIALE INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIZIONE_MATERIALE VARCHAR(200) NOT NULL,
    MARCA VARCHAR(200) NULL,
    CODICE_FORNITORE INT NOT NULL,
    UNITA_MISURA VARCHAR(4) NOT NULL,
    PREZZO_UNITARIO DECIMAL(8,2) NOT NULL,
    DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_MODIFICA TIMESTAMP NULL,
    FOREIGN KEY (CODICE_FORNITORE) REFERENCES ANAGRAFICA_FORNITORI(CODICE_FORNITORE)
    ON DELETE CASCADE -- Se il fornitore viene cancellato anche i suoi materiali verranno eliminati automaticamente
    ON UPDATE CASCADE -- Se il fornitore cambia codice anche i suoi materiali cambieranno codice
);

-- 5. DDL tabella della situazione dei materiali

CREATE TABLE SITUAZIONE_MATERIALI (
    CODICE_MATERIALE INT NOT NULL,
    QUANTITA DECIMAL(8,2) NOT NULL,
    DATA_ULTIMA_MODIFICA TIMESTAMP NOT NULL,
    FOREIGN KEY (CODICE_MATERIALE) REFERENCES ANAGRAFICA_MATERIALI(CODICE_MATERIALE)
    ON DELETE CASCADE -- Se il materiale viene cancellato allora anche la sua situazione viene eliminata
    ON UPDATE CASCADE -- Se il codice materiale viene aggiornato allora anche la sua situazione verrà aggiornata
);

-- 6. DDL vista di incrocio tra la tabella dei fornitori e i materiali

CREATE OR REPLACE VIEW MATERIALI_FORNITORI AS (

    SELECT
        ANAGFOR.CODICE_FORNITORE,
        ANAGFOR.NOME,
        ANAGFOR.COGNOME,
        ANAGFOR.RAGIONE_SOCIALE,
        ANAGFOR.PARTITA_IVA,
        ANAGFOR.CODICE_FISCALE,
        ANAGFOR.CAP,
        ANAGFOR.CODICE_ISTAT,
        ANAGFOR.PHONE_NUMBER,
        ANAGMAT.CODICE_MATERIALE,
        ANAGMAT.DESCRIZIONE_MATERIALE,
        ANAGMAT.MARCA,
        ANAGMAT.UNITA_MISURA,
        ANAGMAT.PREZZO_UNITARIO

    FROM
        ANAGRAFICA_FORNITORI ANAGFOR
    
    INNER JOIN
        ANAGRAFICA_MATERIALI ANAGMAT
    ON
        ANAGFOR.CODICE_FORNITORE = ANAGMAT.CODICE_MATERIALE
)