-- DDL vista per la situazione del fornitore

CREATE OR REPLACE VIEW MATERIALI_FORNITORI AS (

    SELECT
        ANAGFOR.CODICE_FORNITORE,
        ANAGFOR.NOME,
        ANAGFOR.COGNOME,
        ANAGFOR.RAGIONE_SOCIALE,
        ANAGFOR.PARTITA_IVA,
        ANAGFOR.CODICE_FISCALE,
        ANAGFOR.CAP,
        ANAGFOR.CODICE_ISTAT,
        ANAGFOR.INDIRIZZO,
        ANAGFOR.PHONE_NUMBER,
        ANAGMAT.CODICE_MATERIALE,
        ANAGMAT.DESCRIZIONE_MATERIALE,
        ANAGMAT.MARCA,
        ANAGMAT.UNITA_MISURA,
        ANAGMAT.PREZZO_UNITARIO,
        LOC.SIGLA_PROVINCIA,
        LOC.DENOMINAZIONE_PROVINCIA,
        LOC.DENOMINAZIONE_REGIONE,
        LOC.DENOMINAZIONE_LOCALITA

    FROM
        ANAGRAFICA_FORNITORI ANAGFOR
    
    INNER JOIN
        ANAGRAFICA_MATERIALI ANAGMAT
    ON
        ANAGFOR.CODICE_FORNITORE = ANAGMAT.CODICE_MATERIALE

    INNER JOIN
        LOCALITA LOC
    ON
        ANAGFOR.CAP = LOC.CAP AND
        ANAGFOR.CODICE_ISTAT = LOC.CODICE_ISTAT
)