-- DDL di creazione della tabella contente l'anagrafica BUSINESS PARTNER del cliente
CREATE TABLE ANAGRAFICA_CLIENTI (
    CODICE_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    COGNOME VARCHAR(40) NOT NULL,
    CAP INT NOT NULL,
    CODICE_ISTAT INT NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    PHONE_NUMBER INT NULL,
    DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_MODIFICA TIMESTAMP NULL,
    FOREIGN KEY (CODICE_ISTAT) REFERENCES LOCALITA(CODICE_ISTAT)
);