-- DDL vista per la situazione del fornitore

CREATE OR REPLACE VIEW SITUAZIONE_FORNITORE AS (

    SELECT
        CODICE_FORNITORE,
        CODICE_MATERIALE,
        DESCRIZIONE_MATERIALE,
        MARCA,
        UNITA_MISURA,
        SUM(SITMAT.QUANTITA) AS QUANTITA,
        SUM(SITMAT.QUANTITA*ANGMAT.PREZZO_UNITARIO) AS IMPORTO

    FROM
        ANAGRAFICA_MATERIALE ANGMAT

    INNER JOIN
        SITUAZIONE_MATERIALI SITMAT
    ON
        ANGMAT.CODICE_MATERIALE = SITMAT.CODICE_MATERIALE

    GROUP BY
        CODICE_FORNITORE,
        CODICE_MATERIALE,
        DESCRIZIONE_MATERIALE,
        MARCA,
        UNITA_MISURA
)